source 'git@gitlab.alibaba-inc.com:alipods/specs.git'
source 'git@gitlab.alibaba-inc.com:alipods/specs-mirror.git'

def main_pods
    pod 'AliQuickJS', '1.4.0.20200412'
end

target 'WeexSDK' do
    main_pods
end